# Generated by Django 3.1.7 on 2021-04-30 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RevisedApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='backlogs',
            field=models.IntegerField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='dept',
            field=models.CharField(choices=[('CSE', 'CSE'), ('ECE', 'ECE'), ('CIVIL', 'CIVIL'), ('Mechanical', 'Mechanical'), ('EEE', 'EEE'), ('MBA', 'MBA')], max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='dob',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='pass_year',
            field=models.IntegerField(max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='percentage',
            field=models.IntegerField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_no',
            field=models.IntegerField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.IntegerField(choices=[(1, 'student'), (2, 'guest')], default=2),
        ),
        migrations.AlterField(
            model_name='user',
            name='year',
            field=models.CharField(choices=[('III', 'III'), ('IV', 'IV')], max_length=5, null=True),
        ),
    ]
