# Generated by Django 3.1.7 on 2021-05-04 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RevisedApp', '0002_auto_20210430_1251'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
                ('location', models.CharField(max_length=20)),
                ('salary', models.IntegerField(max_length=5, null=True)),
                ('skills', models.CharField(max_length=30)),
                ('job_role', models.CharField(max_length=30)),
                ('eligible_percent', models.IntegerField(max_length=2, null=True)),
                ('eligible_dept', models.CharField(max_length=30)),
                ('year_of_pass', models.IntegerField(max_length=4, null=True)),
                ('last_date', models.DateField(null=True)),
                ('descrip', models.CharField(max_length=250)),
                ('com_image', models.ImageField(default='123.jpg', upload_to='Jobs')),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.IntegerField(choices=[(1, 'admin'), (2, 'student'), (3, 'guest')], default=2),
        ),
    ]
