# Generated by Django 3.1.7 on 2021-05-05 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RevisedApp', '0003_auto_20210504_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.IntegerField(choices=[(1, 'student'), (2, 'guest')], default=2),
        ),
    ]
