# Generated by Django 3.1.7 on 2021-05-06 01:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RevisedApp', '0004_auto_20210505_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobinfo',
            name='com_image',
            field=models.ImageField(default='123.jpg', upload_to='Jobs/'),
        ),
        migrations.CreateModel(
            name='ImProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(default=21)),
                ('impf', models.ImageField(default='123.png', upload_to='Profiles/')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=10)),
                ('uid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
