# Generated by Django 3.1.7 on 2021-05-06 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RevisedApp', '0005_auto_20210506_0720'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImProfile',
        ),
    ]
