# Generated by Django 3.1.7 on 2021-05-07 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RevisedApp', '0007_auto_20210507_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobinfo',
            name='eligible_percent',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='jobinfo',
            name='salary',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='jobinfo',
            name='year_of_pass',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='backlogs',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='pass_year',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='percentage',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_no',
            field=models.IntegerField(null=True),
        ),
    ]
