# Generated by Django 3.1.7 on 2021-05-07 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RevisedApp', '0010_auto_20210507_1724'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coordinator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept', models.CharField(choices=[('CSE', 'CSE'), ('ECE', 'ECE'), ('CIVIL', 'CIVIL'), ('Mechanical', 'Mechanical'), ('EEE', 'EEE'), ('MBA', 'MBA')], max_length=12, null=True)),
                ('phone_no', models.IntegerField(null=True)),
            ],
        ),
    ]
