# Generated by Django 3.1.7 on 2021-05-08 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RevisedApp', '0011_coordinator'),
    ]

    operations = [
        migrations.AddField(
            model_name='coordinator',
            name='cord_name',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
